spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFEhmfxJ4jOaRVBw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJXHThjfqUpygmeZl2txenSyQQwV1bDb7kfNy1WIxIIkxgBw==-hfpe27aXsoe4Fim74w1Uphi5bnNvxe6qsli8OfN0UQY=-i1ipc}}Nf?@4UDS6FV8
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTest2_SPDTech_TEST
ADYEN_CLIENT_KEY=test_YVEP6R7Z2VANFM33GIYGCBPFWEQBQDCZ
ADYEN_HMAC_KEY=46472B660BC4F18326BE089BF24F4D40F68AF12533B868B3CA2993BEDDAD4CEE
